// app/community/housing/listings.ts
export const housingListings = [
  {
    id: 1,
    image: "/housing/apt1.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 2,
    image: "/housing/apt2.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 3,
    image: "/housing/apt3.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 4,
    image: "/housing/apt4.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 5,
    image: "/housing/apt5.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 6,
    image: "/housing/apt6.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 7,
    image: "/housing/apt3.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
  {
    id: 8,
    image: "/housing/apt4.jpg",
    hostName: "Ehsan",
    location: "Burnaby",
    type: "Apartment",
    price: "$2,000 / month",
    duration: "1 year",
    currency: "CAD",
  },
];
